'''
when user picks up a disease, a matrix with states as column and years as rows will be generated by this module for further 
graph. The size of matrix can vary due to the starting and stopping time point or the availability of certain states. 
'''

import sum_week_data
import pandas as pd

data=sum_week_data.group_NYout
pd.set_option('display.max_columns',None)# when checking in ipnb

def heatmap_disease_matrix(disease):
    disease = disease.upper()
    if ' ' in disease:#contain space, change it into +
        disease=disease.replace(" ", "+")
    df_new=data[data['disease']==disease]
    max_year=df_new['year'].max()
    min_year=df_new['year'].min()
    state_list=df_new['loc'].unique()
    df = pd.DataFrame(0, index=range(min_year,max_year+1), columns=state_list)
    for i in df.index:
        df_inner=df_new[df_new['year']==i]
        for j in state_list:
            case=df_inner[df_inner['loc']==j]
            if case.shape[0]!=0:
                case_col=case['number']
                df.loc[i,j]=case_col.iloc[0]            
    return df
